/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO Z40-75
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jamsebelas = new javax.swing.JTextField();
        tHari = new javax.swing.JTextField();
        jamdua = new javax.swing.JTextField();
        jamtiga = new javax.swing.JTextField();
        jamempat = new javax.swing.JTextField();
        jamlima = new javax.swing.JTextField();
        jamenam = new javax.swing.JTextField();
        jamtujuh = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jamdelapan = new javax.swing.JTextField();
        jamsembilan = new javax.swing.JTextField();
        jamsepuluh = new javax.swing.JTextField();
        jamsatu = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jHari = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField68 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        guru11 = new javax.swing.JTextField();
        guru1 = new javax.swing.JTextField();
        guru2 = new javax.swing.JTextField();
        guru3 = new javax.swing.JTextField();
        guru4 = new javax.swing.JTextField();
        guru5 = new javax.swing.JTextField();
        guru6 = new javax.swing.JTextField();
        guru7 = new javax.swing.JTextField();
        guru8 = new javax.swing.JTextField();
        guru9 = new javax.swing.JTextField();
        guru10 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jamsatu1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("JADWAL PELAJARAN XI RPL 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 0, 560, 100);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel2.setText("JAM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 50, 30);

        jamsebelas.setEnabled(false);
        getContentPane().add(jamsebelas);
        jamsebelas.setBounds(90, 740, 300, 26);

        tHari.setEnabled(false);
        getContentPane().add(tHari);
        tHari.setBounds(130, 150, 260, 26);

        jamdua.setEnabled(false);
        getContentPane().add(jamdua);
        jamdua.setBounds(90, 290, 300, 26);

        jamtiga.setEnabled(false);
        getContentPane().add(jamtiga);
        jamtiga.setBounds(90, 340, 300, 26);

        jamempat.setEnabled(false);
        getContentPane().add(jamempat);
        jamempat.setBounds(90, 390, 300, 26);

        jamlima.setEnabled(false);
        getContentPane().add(jamlima);
        jamlima.setBounds(90, 440, 300, 26);

        jamenam.setEnabled(false);
        getContentPane().add(jamenam);
        jamenam.setBounds(90, 490, 300, 26);

        jamtujuh.setEnabled(false);
        jamtujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamtujuhActionPerformed(evt);
            }
        });
        getContentPane().add(jamtujuh);
        jamtujuh.setBounds(90, 540, 300, 26);

        jTextField9.setText("jTextField1");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(90, 540, 84, 26);

        jamdelapan.setEnabled(false);
        getContentPane().add(jamdelapan);
        jamdelapan.setBounds(90, 590, 300, 26);

        jamsembilan.setEnabled(false);
        getContentPane().add(jamsembilan);
        jamsembilan.setBounds(90, 640, 300, 26);

        jamsepuluh.setEnabled(false);
        getContentPane().add(jamsepuluh);
        jamsepuluh.setBounds(90, 690, 300, 26);

        jamsatu.setEnabled(false);
        getContentPane().add(jamsatu);
        jamsatu.setBounds(90, 240, 300, 26);

        jTextField25.setText("jTextField1");
        getContentPane().add(jTextField25);
        jTextField25.setBounds(90, 290, 140, 26);

        jTextField26.setText("jTextField1");
        getContentPane().add(jTextField26);
        jTextField26.setBounds(90, 340, 140, 26);

        jTextField27.setText("jTextField1");
        getContentPane().add(jTextField27);
        jTextField27.setBounds(90, 390, 140, 26);

        jTextField28.setText("jTextField1");
        getContentPane().add(jTextField28);
        jTextField28.setBounds(90, 440, 140, 26);

        jTextField29.setText("jTextField1");
        getContentPane().add(jTextField29);
        jTextField29.setBounds(90, 490, 140, 26);

        jTextField30.setText("jTextField1");
        getContentPane().add(jTextField30);
        jTextField30.setBounds(90, 540, 140, 26);

        jTextField31.setText("jTextField1");
        getContentPane().add(jTextField31);
        jTextField31.setBounds(90, 590, 140, 26);

        jTextField32.setText("jTextField1");
        getContentPane().add(jTextField32);
        jTextField32.setBounds(90, 640, 140, 26);

        jTextField33.setText("jTextField1");
        getContentPane().add(jTextField33);
        jTextField33.setBounds(90, 690, 140, 26);

        jTextField34.setText("jTextField1");
        getContentPane().add(jTextField34);
        jTextField34.setBounds(90, 740, 140, 26);

        jLabel8.setText("11");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 740, 20, 20);

        jLabel9.setText("1");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 240, 10, 20);

        jLabel10.setText("2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 290, 9, 20);

        jLabel11.setText("3");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 340, 9, 20);

        jLabel12.setText("4");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 390, 9, 20);

        jLabel13.setText("5");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 440, 9, 20);

        jLabel14.setText("6");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 490, 9, 20);

        jLabel15.setText("7");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 540, 9, 20);

        jLabel16.setText("8");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 590, 9, 20);

        jLabel17.setText("9");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 640, 9, 20);

        jLabel18.setText("10");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 690, 20, 20);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel19.setText("KELAS    :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 90, 80, 40);

        jHari.setBackground(new java.awt.Color(255, 153, 153));
        jHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Pilih Hari ~", "SENIN", "SELASA", "RABU", "KAMIS", "JUMAT" }));
        jHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHariActionPerformed(evt);
            }
        });
        getContentPane().add(jHari);
        jHari.setBounds(130, 90, 140, 40);

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel20.setText("HARI     :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(20, 150, 80, 30);
        getContentPane().add(jTextField68);
        jTextField68.setBounds(90, 240, 140, 26);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 230, 450, 540);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));
        jPanel2.setLayout(null);

        guru11.setEnabled(false);
        jPanel2.add(guru11);
        guru11.setBounds(570, 740, 200, 26);

        guru1.setEnabled(false);
        jPanel2.add(guru1);
        guru1.setBounds(570, 240, 200, 26);

        guru2.setEnabled(false);
        jPanel2.add(guru2);
        guru2.setBounds(570, 290, 200, 26);

        guru3.setEnabled(false);
        jPanel2.add(guru3);
        guru3.setBounds(570, 340, 200, 26);

        guru4.setEnabled(false);
        jPanel2.add(guru4);
        guru4.setBounds(570, 390, 200, 26);

        guru5.setEnabled(false);
        jPanel2.add(guru5);
        guru5.setBounds(570, 440, 200, 26);

        guru6.setEnabled(false);
        jPanel2.add(guru6);
        guru6.setBounds(570, 490, 200, 26);

        guru7.setEnabled(false);
        jPanel2.add(guru7);
        guru7.setBounds(570, 540, 200, 26);

        guru8.setEnabled(false);
        jPanel2.add(guru8);
        guru8.setBounds(570, 590, 200, 26);

        guru9.setEnabled(false);
        jPanel2.add(guru9);
        guru9.setBounds(570, 640, 200, 26);

        guru10.setEnabled(false);
        guru10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guru10ActionPerformed(evt);
            }
        });
        jPanel2.add(guru10);
        guru10.setBounds(570, 690, 200, 26);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel4.setText("PENGAJAR");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(570, 210, 90, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 770);
        getContentPane().add(jamsatu1);
        jamsatu1.setBounds(90, 240, 300, 26);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel3.setText("JAM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 200, 50, 30);

        setBounds(0, 0, 1022, 825);
    }// </editor-fold>//GEN-END:initComponents

    private void jamtujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamtujuhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jamtujuhActionPerformed

    private void jHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHariActionPerformed
        if (jHari.getSelectedItem().equals("SENIN"))
{
    tHari.setText("SENIN");
    jamsatu.setText("Upacara");
    jamdua.setText("Seni Budaya");
    jamtiga.setText("Seni Budaya");
    jamempat.setText("PPL");
    jamlima.setText("PPL");
    jamenam.setText("Sistel");
    jamtujuh.setText("Sistel");
    jamdelapan.setText("BIG");
    jamsembilan.setText("BIG");
    jamsepuluh.setText("PKN");
    jamsebelas.setText("PKN");
    guru1.setText("SMK TELKOM");
    guru2.setText("Firmansyah Ayatullah,S.Kom.");
    guru3.setText("Firmansyah Ayatullah,S.Kom.");
    guru4.setText("Ifa Choirunisa,S.Kom.");
    guru5.setText("Ifa Choirunisa,S.Kom.");
    guru6.setText("Soelarso,S.T.");
    guru7.setText("Soelarso,S.T.");
    guru8.setText("Larasati Khoirun Nisa,S.Pd.");
    guru9.setText("Larasati Khoirun Nisa,S.Pd.");
    guru10.setText("Fajar Setiawan,S.Pd.");
    guru11.setText("Fajar Setiawan,S.Pd.");
}
else if (jHari.getSelectedItem().equals("SELASA")){
    tHari.setText("SELASA");
    jamsatu.setText("PBO");
    jamdua.setText("PBO");
    jamtiga.setText("PBO");
    jamempat.setText("SI");
    jamlima.setText("SI");
    jamenam.setText("Desktop");
    jamtujuh.setText("Desktop");
    jamdelapan.setText("B.Jawa");
    jamsembilan.setText("B.Jawa");
    jamsepuluh.setText("PAI");
    jamsebelas.setText("PAI");
    guru1.setText("Muhamad Arifin,S.Pd.");
    guru2.setText("Muhamad Arifin,S.Pd.");
    guru3.setText("Muhamad Arifin,S.Pd.");
    guru4.setText("Andik Suharyanto,S.Pd.");
    guru5.setText("Andik Suharyanto,S.Pd.");
    guru6.setText("Hendro Soemarno,S.T.");
    guru7.setText("Hendro Soemarno,S.T.");
    guru8.setText("Sri Chusnul Haniyah,S.Pd.");
    guru9.setText("Sri Chusnul Haniyah,S.Pd.");
    guru10.setText("Achmad Nasikin,M.Pd.");
    guru11.setText("Achmad Nasikin,M.Pd.");
    }
else if (jHari.getSelectedItem().equals("RABU")){
    tHari.setText("RABU");
    jamsatu.setText("PKWU");
    jamdua.setText("PKWU");
    jamtiga.setText("Penjas");
    jamempat.setText("Penjas");
    jamlima.setText("P.WEB");
    jamenam.setText("P.WEB");
    jamtujuh.setText("P.WEB");
    jamdelapan.setText("PAI");
    jamsembilan.setText("Adser");
    jamsepuluh.setText("Adser");
    jamsebelas.setText("Adser");
    guru1.setText("Titik Apriana Dewi,S.Pd.");
    guru2.setText("Titik Apriana Dewi,S.Pd.");
    guru3.setText("Rofiqut Thoriq,S.Pd.");
    guru4.setText("Rofiqut Thoriq,S.Pd.");
    guru5.setText("Firdausa,S.Pd.");
    guru6.setText("Firdausa,S.Pd.");
    guru7.setText("Firdausa,S.Pd.");
    guru8.setText("Achmad Nasikin,S.Pd.");
    guru9.setText("Susanto,S.Kom.");
    guru10.setText("Susanto,S.Kom.");
    guru11.setText("Susanto,S.Kom.");
    }
else if (jHari.getSelectedItem().equals("KAMIS")){
    tHari.setText("KAMIS");
    jamsatu.setText("MAT");
    jamdua.setText("MAT");
    jamtiga.setText("MAT");
    jamempat.setText("BASDAT");
    jamlima.setText("BASDAT");
    jamenam.setText("BASDAT");
    jamtujuh.setText("BK");
    jamdelapan.setText("FISIKA");
    jamsembilan.setText("FISIKA");
    jamsepuluh.setText("Desktop");
    jamsebelas.setText("Desktop");
    guru1.setText("Tulus Andrianto,S.Pd.");
    guru2.setText("Tulus Andrianto,S.Pd.");
    guru3.setText("Tulus Andrianto,S.Pd.");
    guru4.setText("Ifa Choirunisa,S.Kom.");
    guru5.setText("Ifa Choirunisa,S.Kom.");
    guru6.setText("Ifa Choirunisa,S.Kom.");
    guru7.setText("Dra. Peni Wardayani");
    guru8.setText("Drs. Ahmad Khuzaimi");
    guru9.setText("Drs. Ahmad Khuzaimi");
    guru10.setText("Hendro Soemarno,S.T.");
    guru11.setText("Hendro Soemarno,S.T.");
    }
else if (jHari.getSelectedItem().equals("JUMAT")){
    tHari.setText("JUMAT");
    jamsatu.setText("Senam");
    jamdua.setText("PPB");
    jamtiga.setText("PPB");
    jamempat.setText("PPB");
    jamlima.setText("RBJ");
    jamenam.setText("RBJ");
    jamtujuh.setText("RBJ");
    jamdelapan.setText("B.Indo");
    jamsembilan.setText("B.Indo");
    jamsepuluh.setText("B.Indo");
    jamsebelas.setText("-");
    guru1.setText("SMK TELKOM");
    guru2.setText("Hendra Wahyu P.,S.Kom.");
    guru3.setText("Hendra Wahyu P.,S.Kom.");
    guru4.setText("Hendra Wahyu P.,S.Kom.");
    guru5.setText("Hirga Ertama Putra,S.Kom.");
    guru6.setText("Hirga Ertama Putra,S.Kom.");
    guru7.setText("Hirga Ertama Putra,S.Kom.");
    guru8.setText("Tenri Farizatul Wardah,S.Pd.");
    guru9.setText("Tenri Farizatul Wardah,S.Pd.");
    guru10.setText("Tenri Farizatul Wardah,S.Pd.");
    guru11.setText("-");
    }
    }//GEN-LAST:event_jHariActionPerformed

    private void guru10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guru10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guru10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField guru1;
    private javax.swing.JTextField guru10;
    private javax.swing.JTextField guru11;
    private javax.swing.JTextField guru2;
    private javax.swing.JTextField guru3;
    private javax.swing.JTextField guru4;
    private javax.swing.JTextField guru5;
    private javax.swing.JTextField guru6;
    private javax.swing.JTextField guru7;
    private javax.swing.JTextField guru8;
    private javax.swing.JTextField guru9;
    private javax.swing.JComboBox<String> jHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jamdelapan;
    private javax.swing.JTextField jamdua;
    private javax.swing.JTextField jamempat;
    private javax.swing.JTextField jamenam;
    private javax.swing.JTextField jamlima;
    private javax.swing.JTextField jamsatu;
    private javax.swing.JTextField jamsatu1;
    private javax.swing.JTextField jamsebelas;
    private javax.swing.JTextField jamsembilan;
    private javax.swing.JTextField jamsepuluh;
    private javax.swing.JTextField jamtiga;
    private javax.swing.JTextField jamtujuh;
    private javax.swing.JTextField tHari;
    // End of variables declaration//GEN-END:variables
}
